name: bluetooth_gate_control
description: A Flutter app to control a motorized gate via Bluetooth.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_blue_plus: ^1.5.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  logging: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true